/*
 * Techno Engineers
 * Consulta de Usuarios
 * 18/04/2016 -- Autorizo: Rogelio Bernal Escobar //
 * Modificaciones:
 * Sirve para controlar la estructura de la interfaz Consultar Usuarios
 * Numero de metodos en el codigo:0
 * Interfaces:
 */
package Vista;

import Controlador.Manipular;
import Modelo.Conexion;
import Vista.mensajes.Mensajes;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Luiz
 */
public class IConsultaUsuarios extends javax.swing.JPanel {

    boolean bBandera = false;
    /**
     * Creates new form IConsultaUsuarios
     */
    public IConsultaUsuarios() {
        initComponents();
        
        DefaultTableModel objModeloTabla = new DefaultTableModel();
        objModeloTabla.addColumn("ID");
        objModeloTabla.addColumn("NOMBRE");
        objModeloTabla.addColumn("AP. PATERNO");
        objModeloTabla.addColumn("AP. MATERNO");
        jTConsultaBailarines.setModel(objModeloTabla);
        
       /* String datos[] = new String [4];
        String sql="SELECT idusuario,nombre,apellidopaterno,apellidomaterno FROM usuarios '";
         
        try {

            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            if(rs.next()){
                
                datos[0]=rs.getString("idusuario");
                datos[1]=rs.getString("nombre");
                datos[2]=rs.getString("apellidopaterno");
                datos[3]=rs.getString("apellidomaterno");
                
                objModeloTabla.addRow(datos);
            }
            
            jTConsultaBailarines.setModel(objModeloTabla);

        } catch (Exception ex) {
//            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }

    
    void buscar(){
    
        JFrame objFrame=new JFrame();
        Mensajes objMensajes = new Mensajes();
        
        DefaultTableModel objModeloTabla= new DefaultTableModel();
        objModeloTabla.addColumn("ID");
        objModeloTabla.addColumn("NOMBRE");
        objModeloTabla.addColumn("AP. PATERNO");
        objModeloTabla.addColumn("AP. MATERNO");
        jTConsultaBailarines.setModel(objModeloTabla);//las agregamos a la tabla
        
        String datos[] = new String [4];
        String sql="SELECT idusuario,nombre,apellidopaterno,apellidomaterno FROM usuarios WHERE nombre= '" + jTNombreBailarin.getText() +"'";
         
        try {

            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            if(rs.next()){
              
                bBandera = true;
                
                datos[0]=rs.getString("idusuario");
                datos[1]=rs.getString("nombre");
                datos[2]=rs.getString("apellidopaterno");
                datos[3]=rs.getString("apellidomaterno");
                
                objModeloTabla.addRow(datos);
            }else{
               objMensajes.falla(objFrame);
            }
            
            
            jTConsultaBailarines.setModel(objModeloTabla);

            
            
        } catch (Exception ex) {
              objMensajes.falla(objFrame);
//            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBConsultaBailarines = new javax.swing.JButton();
        jBRegistraBailarines = new javax.swing.JButton();
        jPConsultaBailarines = new javax.swing.JPanel();
        jBBuscar = new javax.swing.JButton();
        jTNombreBailarin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTConsultaBailarines = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(537, 371));

        jBConsultaBailarines.setText("Consultar Bailarines");
        jBConsultaBailarines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultaBailarinesActionPerformed(evt);
            }
        });

        jBRegistraBailarines.setText("Registrar Bailarines");
        jBRegistraBailarines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistraBailarinesActionPerformed(evt);
            }
        });

        jPConsultaBailarines.setBackground(new java.awt.Color(255, 255, 255));
        jPConsultaBailarines.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jTNombreBailarin.setPreferredSize(new java.awt.Dimension(6, 30));
        jTNombreBailarin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNombreBailarinKeyTyped(evt);
            }
        });

        jTConsultaBailarines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTConsultaBailarines);

        javax.swing.GroupLayout jPConsultaBailarinesLayout = new javax.swing.GroupLayout(jPConsultaBailarines);
        jPConsultaBailarines.setLayout(jPConsultaBailarinesLayout);
        jPConsultaBailarinesLayout.setHorizontalGroup(
            jPConsultaBailarinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPConsultaBailarinesLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jBBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTNombreBailarin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPConsultaBailarinesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPConsultaBailarinesLayout.setVerticalGroup(
            jPConsultaBailarinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPConsultaBailarinesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPConsultaBailarinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNombreBailarin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jBConsultaBailarines)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBRegistraBailarines))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPConsultaBailarines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConsultaBailarines, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBRegistraBailarines, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPConsultaBailarines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBConsultaBailarinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultaBailarinesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBConsultaBailarinesActionPerformed

    private void jBRegistraBailarinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistraBailarinesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBRegistraBailarinesActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
        JFrame objFrame=new JFrame();
        Mensajes objMensajes = new Mensajes();
        
        if (jTNombreBailarin.getText().isEmpty()){
            
            objMensajes.falla(objFrame);
            
        }else{
        
            buscar();
            Manipular.limpiaCajas(jTNombreBailarin);
            if(bBandera == true){
               objMensajes.exito(objFrame);
            }
            con.desconectar(conn);
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jTNombreBailarinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNombreBailarinKeyTyped
        // TODO add your handling code here:
        if(!Character.isAlphabetic(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar()))
        {
                 Toolkit.getDefaultToolkit().beep();
                 evt.consume();
        }
    }//GEN-LAST:event_jTNombreBailarinKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBConsultaBailarines;
    private javax.swing.JButton jBRegistraBailarines;
    private javax.swing.JPanel jPConsultaBailarines;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTConsultaBailarines;
    private javax.swing.JTextField jTNombreBailarin;
    // End of variables declaration//GEN-END:variables
    //variables globales
    Conexion con = new Conexion();
    Connection conn = con.Conecta("localhost", "trajin", "root", "123456");
}
