/*
 * Techno Engineers
 * Modificar Cuadro
 * 24/04/2016 -- Autorizo: Rogelio Angel Bernal Escobar // Carlos Jordan Trujillo Figueroa
 * Modificación de cuadros
 * Sirve para modificar los registros de cuadros
 * Numero de metodos en el código: 
 * Interfaces: ModificarCuadros
 */
package Vista;
import Controlador.ManipulaInterfaces;
import Controlador.Manipular;
import Controlador.ValidaDatosIngreso;
import Controlador.Validaciones;
import Modelo.Conexion;
import Modelo.Querys;
import Vista.mensajes.Mensajes;
import java.util.ArrayList;

/**
 *
 * @author Roy
 */
public class ModificarCuadros extends javax.swing.JFrame {

    static ModificarCuadros objModificarC = new ModificarCuadros();    
    /**
     * Creates new form ModificarCuadros
     */
    public ModificarCuadros() {
        initComponents();
    }
    
    public int validaCamposVacios()
    {
        if (jTFIdCuadro.getText().equals(""))
        {
            Mensajes.falla(this, "Selecciona un id de cuadro valido");
            jTFIdCuadro.requestFocus();
            return 1;
        } else if (jTFNombreCuadroNew.getText().equals(""))
        {
            Mensajes.falla(this, "Selecciona un nombre de cuadro valido");
            jTFNombreCuadroNew.requestFocus();
            return 1;
        } else if (jTFTiempoNew.getText().equals(""))
        {
            Mensajes.falla(this, "Selecciona un tiempo valido");
            jTFTiempoNew.requestFocus();
            return 1;
        }
        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNombreCuadro = new javax.swing.JLabel();
        jTFNombreCuadroNew = new javax.swing.JTextField();
        jLTempo = new javax.swing.JLabel();
        jTFTiempoNew = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLIDcuadro = new javax.swing.JLabel();
        jTFIdCuadro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificar Cuadros");

        jLNombreCuadro.setText("Nuevo nombre del cuadro:");

        jTFNombreCuadroNew.setEnabled(false);
        jTFNombreCuadroNew.setPreferredSize(new java.awt.Dimension(6, 30));
        jTFNombreCuadroNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreCuadroNewActionPerformed(evt);
            }
        });
        jTFNombreCuadroNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFNombreCuadroNewKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFNombreCuadroNewKeyTyped(evt);
            }
        });

        jLTempo.setText("Nuevo Tiempo de cambio: ");

        jTFTiempoNew.setEnabled(false);
        jTFTiempoNew.setPreferredSize(new java.awt.Dimension(6, 30));
        jTFTiempoNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTiempoNewActionPerformed(evt);
            }
        });
        jTFTiempoNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFTiempoNewKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFTiempoNewKeyTyped(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.setEnabled(false);
        jBGuardar.setPreferredSize(new java.awt.Dimension(120, 50));
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        jBGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBGuardarKeyPressed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.setPreferredSize(new java.awt.Dimension(120, 50));
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jLIDcuadro.setText("Id del Cuadro a modificar:");

        jTFIdCuadro.setPreferredSize(new java.awt.Dimension(6, 30));
        jTFIdCuadro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFIdCuadroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFIdCuadroKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLTempo)
                        .addGap(19, 19, 19)
                        .addComponent(jTFTiempoNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLIDcuadro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLNombreCuadro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTFNombreCuadroNew, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTFIdCuadro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFIdCuadro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLIDcuadro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombreCuadro)
                    .addComponent(jTFNombreCuadroNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTempo)
                    .addComponent(jTFTiempoNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNombreCuadroNewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNombreCuadroNewKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            Manipular.cambioObj(jTFTiempoNew);
        }
    }//GEN-LAST:event_jTFNombreCuadroNewKeyPressed

    private void jTFNombreCuadroNewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNombreCuadroNewKeyTyped
        ValidaDatosIngreso.cadena(evt);
        int ilimite=49;
        if (jTFNombreCuadroNew.getText().length() == ilimite)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTFNombreCuadroNewKeyTyped

    private void jTFTiempoNewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFTiempoNewKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            Manipular.cambioObj(jBGuardar);
        }
    }//GEN-LAST:event_jTFTiempoNewKeyPressed

    private void jTFTiempoNewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFTiempoNewKeyTyped
        ValidaDatosIngreso.entero(evt);
        int ilimite=9;
        if (jTFTiempoNew.getText().length() == ilimite)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTFTiempoNewKeyTyped

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        int r = this.validaCamposVacios();
        if (r == 0)
        {
            Conexion con = new Conexion();
            con.Conecta("localhost", "trajin", "root", "123456");
            
            if (con.con != null)
            {
                String s= "nombre, tiempocambio";
                String datos = "'" + jTFNombreCuadroNew.getText() + "','" + jTFTiempoNew.getText() + "'";
               
                Querys objQ = new Querys();
                objQ.Modificar(con.con, "cuadros", s, datos, "idcuadro = " + jTFIdCuadro.getText());

                try
                {
                    con.con.close();
                    Mensajes.exito(this);

                } catch (Exception ex)
                {
                    Mensajes.msj(this, "Error en DB... " + ex.getMessage());
                }
            }
            jBCancelarActionPerformed(evt);
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBGuardarKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            jBGuardarActionPerformed(null);
        }
    }//GEN-LAST:event_jBGuardarKeyPressed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        Manipular.deshabilitaObj(false, jTFTiempoNew, jBGuardar, jTFNombreCuadroNew);
        Manipular.limpiaCajas(jTFNombreCuadroNew, jTFTiempoNew, jTFIdCuadro);
        jTFIdCuadro.requestFocus();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTFIdCuadroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFIdCuadroKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '\n')
        {
            Manipular.cambioObj(jTFNombreCuadroNew);
        }
    }//GEN-LAST:event_jTFIdCuadroKeyPressed

    private void jTFIdCuadroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFIdCuadroKeyTyped
        // TODO add your handling code here:
        ValidaDatosIngreso.entero(evt);
        int ilimite=9;
        if (jTFIdCuadro.getText().length() == ilimite)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTFIdCuadroKeyTyped

    private void jTFTiempoNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTiempoNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTiempoNewActionPerformed

    private void jTFNombreCuadroNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreCuadroNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreCuadroNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarCuadros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarCuadros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarCuadros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarCuadros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                objModificarC.setTitle("Modificación de Cuadros");
                objModificarC.setVisible(true);
                objModificarC.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JLabel jLIDcuadro;
    private javax.swing.JLabel jLNombreCuadro;
    private javax.swing.JLabel jLTempo;
    private javax.swing.JTextField jTFIdCuadro;
    private javax.swing.JTextField jTFNombreCuadroNew;
    private javax.swing.JTextField jTFTiempoNew;
    // End of variables declaration//GEN-END:variables
}
