/*
 * Techno Engineers
 * RecuperarContrasena
 * 12/04/2016 -- Autorizo: Marvin Atzael Hernández Benítez // Lider de proyecto
 * Modificaciones: 
 * Sirve paracambiar o actualizar la contraseña
 * Numero de métodos en el codigo: 0
 * Login: 
 */
package Vista;

import Controlador.Manipular;
import Controlador.ValidaDatosIngreso;
import javax.swing.JFrame;
import Modelo.UsuariosModelo;
import Modelo.UsuariosDatosEncapsulados;
import Vista.mensajes.Mensajes;

/**
 *
 * @author mgool
 */
public class RecuperarContrasena extends javax.swing.JFrame
{

    /**
     * Creates new form RecuperarContrasena
     */
    public RecuperarContrasena()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLFContrasena = new javax.swing.JLabel();
        jLFRepetirContrasena = new javax.swing.JLabel();
        jBPreguntasSeguras = new javax.swing.JButton();
        jPFNuevaContrasena = new javax.swing.JPasswordField();
        jPFRepitaContrasena = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPFUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLFContrasena.setText("Nueva contraseña:");

        jLFRepetirContrasena.setText("Repita contraseña:");

        jBPreguntasSeguras.setText("Cambiar contraseña");
        jBPreguntasSeguras.setPreferredSize(new java.awt.Dimension(120, 50));
        jBPreguntasSeguras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPreguntasSegurasActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario:");

        jPFUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPFUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLFContrasena)
                        .addComponent(jLFRepetirContrasena)
                        .addComponent(jPFRepitaContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(jPFNuevaContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(jBPreguntasSeguras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jPFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jPFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLFContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPFNuevaContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLFRepetirContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPFRepitaContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jBPreguntasSeguras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPreguntasSegurasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBPreguntasSegurasActionPerformed
    {//GEN-HEADEREND:event_jBPreguntasSegurasActionPerformed
        ValidaDatosIngreso nombre = new ValidaDatosIngreso();
        JFrame objFrame = new JFrame("Dialogo de mensajes");
        UsuariosDatosEncapsulados objUsuariosDatosEncapsulados = new UsuariosDatosEncapsulados();

        while (ValidaDatosIngreso.bUsuarioValido != true)
        {
            nombre.ValidaCadenaAlfanumerica(jPFUsuario.getText(), "usuario", "usuario"); //Usuario de 5 digitos o más, pero no más de 100. Y letras con numeros.
            break;
        }

        objUsuariosDatosEncapsulados.setNombreUsuario(jPFUsuario.getText());
        if (ValidaDatosIngreso.bUsuarioValido == true)
        {

            objUsuariosDatosEncapsulados.setContrasena(jPFRepitaContrasena.getText());
            if (jPFNuevaContrasena.getText().equals(jPFRepitaContrasena.getText()))
            {
                int n = UsuariosModelo.recuperarContrasenia(objUsuariosDatosEncapsulados);
                if (n == 0)
                {
                    Mensajes.exito(objFrame);
                    System.out.println("Contraseñas iguales ");
                    System.out.println("" + jPFUsuario);
                } else
                {
                    Mensajes.falla(objFrame, "No se pudo realizar la accion solicitada");
                    System.out.println("error");
                }

            } else
            {
                Mensajes.falla(objFrame, "La contraseña no coincide, verifique porfavor!");
                System.out.println("no coinciden las contraseñas");
            }
            ValidaDatosIngreso.bCorreoValido = false;
            ValidaDatosIngreso.bUsuarioValido = false;
            
        }
        Manipular.limpiaCajas(jPFUsuario, jPFNuevaContrasena,jPFRepitaContrasena);
    }//GEN-LAST:event_jBPreguntasSegurasActionPerformed

    private void jPFNuevaContrasenaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jPFNuevaContrasenaKeyPressed
    {//GEN-HEADEREND:event_jPFNuevaContrasenaKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            Manipular.cambioObj(jPFRepitaContrasena);
        }
    }//GEN-LAST:event_jPFNuevaContrasenaKeyPressed

    private void jPFRepitaContrasenaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jPFRepitaContrasenaKeyPressed
    {//GEN-HEADEREND:event_jPFRepitaContrasenaKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            Manipular.cambioObj(jBPreguntasSeguras);
        }
    }//GEN-LAST:event_jPFRepitaContrasenaKeyPressed

    private void jPFUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPFUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPFUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new RecuperarContrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPreguntasSeguras;
    private javax.swing.JLabel jLFContrasena;
    private javax.swing.JLabel jLFRepetirContrasena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPFNuevaContrasena;
    private javax.swing.JPasswordField jPFRepitaContrasena;
    private javax.swing.JTextField jPFUsuario;
    // End of variables declaration//GEN-END:variables
}
