/*
 * Techno Engineers
 * VerificarUsuario
 * 12/04/2016 -- Autorizo: Marvin Atzael Hernández Benítez // Lider de proyecto
 * Modificaciones: 
 * Sirve para verificar usuario que cambuará la contraseña
 * Numero de métodos en el codigo: 0
 * VerificarPreguntas: 
 */
package Vista;

import Controlador.Manipular;
import Controlador.ValidaDatosIngreso;
import Modelo.UsuariosDatosEncapsulados;
import Modelo.UsuariosModelo;
import Vista.mensajes.Mensajes;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class VerificarUsuario extends javax.swing.JFrame
{

    public VerificarUsuario()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLFUsuario = new javax.swing.JLabel();
        jTFUsuario = new javax.swing.JTextField();
        jBComprobarPreguntas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLFUsuario.setText("Usuario: ");

        jTFUsuario.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFUsuarioKeyPressed(evt);
            }
        });

        jBComprobarPreguntas.setText("Comprobar");
        jBComprobarPreguntas.setPreferredSize(new java.awt.Dimension(120, 50));
        jBComprobarPreguntas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBComprobarPreguntasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFUsuario)
                    .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBComprobarPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLFUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBComprobarPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBComprobarPreguntasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBComprobarPreguntasActionPerformed
    {//GEN-HEADEREND:event_jBComprobarPreguntasActionPerformed
        ValidaDatosIngreso nombre = new ValidaDatosIngreso();
        JFrame objFrame = new JFrame("Dialogo de mensajes");
        UsuariosDatosEncapsulados objUsuariosDatosEncapsulados = new UsuariosDatosEncapsulados();

        while (ValidaDatosIngreso.bUsuarioValido == false)
        {
            nombre.ValidaCadenaAlfanumerica(jTFUsuario.getText(), "usuario", "usuario"); //Usuario de 5 digitos o más, pero no más de 100. Y letras con numeros.
            break;
        }
        objUsuariosDatosEncapsulados.setNombreUsuario(jTFUsuario.getText());

        if (ValidaDatosIngreso.bUsuarioValido == true)
        {

            int n = UsuariosModelo.consultarUsuarios(objUsuariosDatosEncapsulados);

            if (n == 0)
            {
                VerificarPreguntas objVerificarPreguntas = new VerificarPreguntas();
                objVerificarPreguntas.setVisible(true);

            } else
            {
                Mensajes.falla(objFrame, "No se encontró el usuario.");
            }
        }
        Manipular.limpiaCajas(jTFUsuario);
        ValidaDatosIngreso.bUsuarioValido = false;
    }//GEN-LAST:event_jBComprobarPreguntasActionPerformed

    private void jTFUsuarioKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFUsuarioKeyPressed
    {//GEN-HEADEREND:event_jTFUsuarioKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            Manipular.cambioObj(jBComprobarPreguntas);
        }
    }//GEN-LAST:event_jTFUsuarioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VerificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VerificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VerificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VerificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VerificarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBComprobarPreguntas;
    private javax.swing.JLabel jLFUsuario;
    private javax.swing.JTextField jTFUsuario;
    // End of variables declaration//GEN-END:variables
}
