/*
 * Techno Engineers
 * VerificarUsuario
 * 12/04/2016 -- Autorizo: Marvin Atzael Hernández Benítez // Lider de proyecto
 * Modificaciones: 
 * Sirve para recuperar contraseña me diante preguntas
 * Numero de métodos en el codigo: 0
 * RecuperarContrasena: 
 */
package Vista;

import Controlador.Manipular;
import Modelo.UsuariosDatosEncapsulados;
import Modelo.UsuariosModelo;
import Vista.mensajes.Mensajes;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;

public class VerificarPreguntas extends javax.swing.JFrame
{

    public VerificarPreguntas()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLNombre = new javax.swing.JLabel();
        jLFLugarNacimiento = new javax.swing.JLabel();
        jLFCorreo = new javax.swing.JLabel();
        jBPreguntasSeguras = new javax.swing.JButton();
        jDCFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jTFLugarNacimiento = new javax.swing.JTextField();
        jTFCorreo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLNombre.setText("Fecha de nacimiento: ");

        jLFLugarNacimiento.setText("Lugar de nacimiento:");

        jLFCorreo.setText("Correo de registro:");

        jBPreguntasSeguras.setText("Verificar");
        jBPreguntasSeguras.setPreferredSize(new java.awt.Dimension(120, 50));
        jBPreguntasSeguras.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBPreguntasSegurasActionPerformed(evt);
            }
        });

        jDCFechaNacimiento.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jDCFechaNacimientoKeyPressed(evt);
            }
        });

        jTFLugarNacimiento.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFLugarNacimientoKeyPressed(evt);
            }
        });

        jTFCorreo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFCorreoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFLugarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLFCorreo)
                        .addComponent(jLFLugarNacimiento)
                        .addComponent(jLNombre)
                        .addComponent(jBPreguntasSeguras, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(jDCFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDCFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLFLugarNacimiento)
                .addGap(9, 9, 9)
                .addComponent(jTFLugarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLFCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBPreguntasSeguras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPreguntasSegurasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBPreguntasSegurasActionPerformed
    {//GEN-HEADEREND:event_jBPreguntasSegurasActionPerformed
        JFrame objFrame = new JFrame("Dialogo de mensajes");
        UsuariosDatosEncapsulados objUsuariosDatosEncapsulados = new UsuariosDatosEncapsulados();
        String sFechaNacimiento = new SimpleDateFormat("yyyy/MM/dd").format(jDCFechaNacimiento.getDate());
        
        objUsuariosDatosEncapsulados.setsFechaNacimiento(sFechaNacimiento);
        objUsuariosDatosEncapsulados.setsLugarNacimiento(jTFLugarNacimiento.getText());
        objUsuariosDatosEncapsulados.setsEmail(jTFCorreo.getText());

        int iResultado=UsuariosModelo.verificarPreguntas(objUsuariosDatosEncapsulados);
        
        if (iResultado==0)
        {
            Mensajes.exito(objFrame);
            RecuperarContrasena objRecuperarContrasena = new RecuperarContrasena();
            objRecuperarContrasena.setVisible(true);
            this.dispose();
        } else
        {
            Mensajes.falla(objFrame);
        }
                Manipular.limpiaCajas(jTFLugarNacimiento,jTFCorreo);
    }//GEN-LAST:event_jBPreguntasSegurasActionPerformed

    private void jDCFechaNacimientoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jDCFechaNacimientoKeyPressed
    {//GEN-HEADEREND:event_jDCFechaNacimientoKeyPressed
         if(evt.getKeyChar() == '\n')
        {
             Manipular.cambioObj(jTFLugarNacimiento);
        }
    }//GEN-LAST:event_jDCFechaNacimientoKeyPressed

    private void jTFCorreoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFCorreoKeyPressed
    {//GEN-HEADEREND:event_jTFCorreoKeyPressed
        if(evt.getKeyChar() == '\n')
        {
             Manipular.cambioObj(jBPreguntasSeguras);
        }
    }//GEN-LAST:event_jTFCorreoKeyPressed

    private void jTFLugarNacimientoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFLugarNacimientoKeyPressed
    {//GEN-HEADEREND:event_jTFLugarNacimientoKeyPressed
        if(evt.getKeyChar() == '\n')
        {
             Manipular.cambioObj(jTFCorreo);
        }
    }//GEN-LAST:event_jTFLugarNacimientoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VerificarPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VerificarPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VerificarPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VerificarPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VerificarPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPreguntasSeguras;
    private com.toedter.calendar.JDateChooser jDCFechaNacimiento;
    private javax.swing.JLabel jLFCorreo;
    private javax.swing.JLabel jLFLugarNacimiento;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JTextField jTFCorreo;
    private javax.swing.JTextField jTFLugarNacimiento;
    // End of variables declaration//GEN-END:variables
}
